AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UnlockUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: unlock_unit.lambda_handler
      Runtime: python3.8
      CodeUri: src/unlock_unit/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSESFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: StorageUnits
          SES_REGION: eu-west-1

  LockUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lock_unit.lambda_handler
      Runtime: python3.8
      CodeUri: src/lock_unit/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: StorageUnits

  ShareAccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: share_access.lambda_handler
      Runtime: python3.8
      CodeUri: src/share_access/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: SharedAccess

  StorageUnitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StorageUnits
      AttributeDefinitions:
        - AttributeName: unit_id
          AttributeType: S
      KeySchema:
        - AttributeName: unit_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SharedAccessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SharedAccess
      AttributeDefinitions:
        - AttributeName: unit_id
          AttributeType: S
        - AttributeName: shared_user_id
          AttributeType: S
      KeySchema:
        - AttributeName: unit_id
          KeyType: HASH
        - AttributeName: shared_user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
