version = 0.1
[default.deploy.parameters]
stack_name = "storage-solution"
resolve_s3 = true
s3_prefix = "storage-solution"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
