version = 0.1
[default.deploy.parameters]
stack_name = "serverless-convenient-storage-solution"
resolve_s3 = true
s3_prefix = "serverless-convenient-storage-solution"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "UserPoolAdminGroupName=\"apiAdmins\""
