version = 0.1
[default.deploy.parameters]
stack_name = "payment-billing-stack"
resolve_s3 = true
s3_prefix = "payment-billing-stack"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []